### ISSUE TITLE
why throw Unhandled Exception????

### ISSUE THREAD

**Issue by juedi998** [BaristaLabs/chrome-dev-tools-sample#2]
Hi, i deploying in the project with chrome-dev-tools-runtime; in execute the Test project, that throw Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request.    can u tell me so why? My development environment is vs 2017 community + windows 10 Professional + .net Core 2.1 .

Exception info:

Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: 无法与服务器建立连接
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ChromeDevToolsRuntimeCLI.Program.<GetSessions>d__1.MoveNext() in C:\Users\tyb\Desktop\chrome-dev-tools-runtime-master\ChromeDevToolsCLI\Program.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ChromeDevToolsRuntimeCLI.Program.<Main>d__0.MoveNext() in C:\Users\tyb\Desktop\chrome-dev-tools-runtime-master\ChromeDevToolsCLI\Program.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ChromeDevToolsRuntimeCLI.Program.<Main>(String[] args)

**Comment by Oceanswave** [comment]
Before running the example CLI app , ensure that you've started a Chrome instance that enables remote debugging on port 9223,

C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9223
